# Generated by Django 4.2 on 2026-06-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Номер паспорта'),
        ),
    ]
